//! Sandboxed, durable update and rollback coordination.
//!
//! The coordinator is intentionally driven by an explicit [`Installation`].
//! It never discovers an installed runtime or starts an executable. A caller
//! supplies compatibility and health observations, keeping qualification
//! deterministic and real activation behind its human gate.

use std::{
    collections::BTreeMap,
    fmt, fs,
    io::{self, Read},
    path::{Component, Path, PathBuf},
    time::{SystemTime, UNIX_EPOCH},
};

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::installation::{AutostartBackend, AutostartEntry, InstallError, Installation};

const UPDATE_SCHEMA_VERSION: u32 = 1;
const TRANSACTION_FILE: &str = "update-transaction.json";
const RECEIPT_FILE: &str = "update-receipt.json";
const AUTOSTART_OWNER: &str = "runnermesh-v01";

/// A complete update input. `expected_payload_sha256` is a semantic digest
/// of the staged directory, generated by [`payload_sha256`].
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct UpdateRequest {
    pub version: String,
    pub payload: PathBuf,
    pub expected_payload_sha256: String,
    pub compatible: bool,
}

impl UpdateRequest {
    pub fn new(
        version: impl Into<String>,
        payload: impl Into<PathBuf>,
        expected_payload_sha256: impl Into<String>,
    ) -> Self {
        Self {
            version: version.into(),
            payload: payload.into(),
            expected_payload_sha256: expected_payload_sha256.into(),
            compatible: true,
        }
    }
}

/// Durable update phase. `Intent` is written before copying the payload;
/// `Switched` is written after the active pointer changes. Any interruption
/// before `Committed` reconciles to the previously validated version.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum UpdatePhase {
    Intent,
    ReadyToActivate,
    DeferredForActiveJob,
    Switched,
    Committed,
    RolledBack,
}

impl UpdatePhase {
    fn is_terminal(self) -> bool {
        matches!(self, Self::Committed | Self::RolledBack)
    }
}

/// The journal contains no source path: it binds only the immutable desired
/// version, its checksum, and the old active version needed for recovery.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct UpdateTransaction {
    pub schema_version: u32,
    pub transaction_id: String,
    pub previous_version: String,
    pub requested_version: String,
    pub payload_sha256: String,
    pub phase: UpdatePhase,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum UpdateOutcome {
    Committed,
    RolledBack,
    DeferredForActiveJob,
    RecoveredRollback,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct UpdateReceipt {
    pub schema_version: u32,
    pub transaction_id: String,
    pub outcome: UpdateOutcome,
    pub active_version: String,
    pub poststate_reconciled: bool,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ReconcileReceipt {
    pub transaction_id: String,
    pub outcome: UpdateOutcome,
    pub active_version: String,
}

/// A non-executing health observation. The coordinator additionally proves
/// that the selected immutable agent file still exists before commit.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum HealthObservation {
    Healthy,
    Unhealthy(String),
}

/// A complete cumulative audit of the productization-only surfaces. It
/// intentionally excludes tray, probes, and real runner lifecycle evidence.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CumulativeProductizationAudit {
    pub ownership_ledger_valid: bool,
    pub foreign_content_refusal_enforced: bool,
    pub drift_refusal_enforced: bool,
    pub atomic_transition_journal_valid: bool,
    pub autostart_target_owned: bool,
    pub active_pointer_valid: bool,
    pub durable_transaction_reconciled: bool,
    pub rollback_state_recoverable: bool,
}

/// Explicit-root update coordinator for fixture and future install-runtime
/// callers. Calling it alone does not activate a production installation.
#[derive(Clone, Debug)]
pub struct UpdateCoordinator {
    installation: Installation,
}

impl UpdateCoordinator {
    pub fn new(installation: Installation) -> Self {
        Self { installation }
    }

    pub fn installation(&self) -> &Installation {
        &self.installation
    }

    /// Checks compatibility and the exact payload checksum, records durable
    /// intent, copies into an immutable version slot, and only then reports
    /// `READY_TO_ACTIVATE`.
    pub fn stage(&self, request: &UpdateRequest) -> Result<UpdateTransaction, UpdateError> {
        if !request.compatible {
            return Err(UpdateError::Incompatible);
        }
        let actual_sha256 = payload_sha256(&request.payload)?;
        if actual_sha256 != request.expected_payload_sha256 {
            return Err(UpdateError::ChecksumMismatch {
                expected: request.expected_payload_sha256.clone(),
                actual: actual_sha256,
            });
        }

        self.ensure_no_inflight_transaction()?;
        let state = self.installation.state()?;
        let previous_version = state.active_version.ok_or(UpdateError::NoPreviousVersion)?;
        if previous_version == request.version {
            return Err(UpdateError::SameVersion(request.version.clone()));
        }
        if state.versions.contains_key(&request.version) {
            return Err(UpdateError::VersionAlreadyInstalled(
                request.version.clone(),
            ));
        }

        let mut transaction = UpdateTransaction {
            schema_version: UPDATE_SCHEMA_VERSION,
            transaction_id: unique_transaction_id(),
            previous_version,
            requested_version: request.version.clone(),
            payload_sha256: actual_sha256,
            phase: UpdatePhase::Intent,
        };
        self.write_transaction(&transaction)
            .map_err(|error| UpdateError::DamagedJournal(format!("intent persistence: {error}")))?;

        self.installation
            .install(&request.version, &request.payload)
            .map_err(|error| UpdateError::DamagedJournal(format!("immutable staging: {error}")))?;
        transaction.phase = UpdatePhase::ReadyToActivate;
        self.write_transaction(&transaction).map_err(|error| {
            UpdateError::DamagedJournal(format!("ready-to-activate persistence: {error}"))
        })?;
        Ok(transaction)
    }

    /// Advances a ready transaction only when no active job exists. A failed
    /// health observation restores the prior validated version before a
    /// truthful rollback receipt is written.
    pub fn activate(
        &self,
        active_job_present: bool,
        health: HealthObservation,
    ) -> Result<UpdateReceipt, UpdateError> {
        let mut transaction = self.read_transaction()?.ok_or(UpdateError::NoTransaction)?;
        match transaction.phase {
            UpdatePhase::ReadyToActivate | UpdatePhase::DeferredForActiveJob => {}
            phase => return Err(UpdateError::UnexpectedPhase(phase)),
        }

        if active_job_present {
            transaction.phase = UpdatePhase::DeferredForActiveJob;
            self.write_transaction(&transaction)?;
            return self.write_receipt(
                &transaction,
                UpdateOutcome::DeferredForActiveJob,
                &transaction.previous_version,
            );
        }

        if transaction.phase == UpdatePhase::DeferredForActiveJob {
            transaction.phase = UpdatePhase::ReadyToActivate;
            self.write_transaction(&transaction)?;
        }

        self.installation
            .select_active(&transaction.requested_version)?;
        transaction.phase = UpdatePhase::Switched;
        self.write_transaction(&transaction)?;

        if self.verify_health(&health).is_err() {
            self.installation
                .select_active(&transaction.previous_version)?;
            transaction.phase = UpdatePhase::RolledBack;
            self.write_transaction(&transaction)?;
            return self.write_receipt(
                &transaction,
                UpdateOutcome::RolledBack,
                &transaction.previous_version,
            );
        }

        transaction.phase = UpdatePhase::Committed;
        self.write_transaction(&transaction)?;
        self.write_receipt(
            &transaction,
            UpdateOutcome::Committed,
            &transaction.requested_version,
        )
    }

    /// Treats every incomplete transaction as an interruption. The only safe
    /// automatic action is to recover the old version; an unexpected third
    /// active version is external drift and is refused.
    pub fn reconcile(&self) -> Result<ReconcileReceipt, UpdateError> {
        let mut transaction = self.read_transaction()?.ok_or(UpdateError::NoTransaction)?;
        let current = self.active_version()?;

        if transaction.phase.is_terminal() {
            let expected = match transaction.phase {
                UpdatePhase::Committed => &transaction.requested_version,
                UpdatePhase::RolledBack => &transaction.previous_version,
                _ => unreachable!("terminal phase is exhaustive"),
            };
            if &current != expected {
                return Err(UpdateError::ActiveVersionDrift {
                    expected: expected.clone(),
                    actual: current,
                });
            }
            let outcome = match transaction.phase {
                UpdatePhase::Committed => UpdateOutcome::Committed,
                UpdatePhase::RolledBack => UpdateOutcome::RolledBack,
                _ => unreachable!("terminal phase is exhaustive"),
            };
            self.ensure_terminal_receipt(&transaction, outcome, expected)?;
            return Ok(ReconcileReceipt {
                transaction_id: transaction.transaction_id,
                outcome,
                active_version: expected.clone(),
            });
        }

        if current != transaction.previous_version && current != transaction.requested_version {
            return Err(UpdateError::ActiveVersionDrift {
                expected: transaction.previous_version,
                actual: current,
            });
        }
        if current != transaction.previous_version {
            self.installation
                .select_active(&transaction.previous_version)?;
        }
        transaction.phase = UpdatePhase::RolledBack;
        self.write_transaction(&transaction)?;
        self.write_receipt(
            &transaction,
            UpdateOutcome::RecoveredRollback,
            &transaction.previous_version,
        )?;
        Ok(ReconcileReceipt {
            transaction_id: transaction.transaction_id,
            outcome: UpdateOutcome::RecoveredRollback,
            active_version: transaction.previous_version,
        })
    }

    /// Checks the complete post-update productization contract with no runner,
    /// process, registry, or production-runtime mutation.
    pub fn cumulative_productization_audit(
        &self,
        autostart: &impl AutostartBackend,
    ) -> Result<CumulativeProductizationAudit, UpdateError> {
        let state = self.installation.state()?;
        let active = state.active_version.ok_or(UpdateError::NoPreviousVersion)?;
        let active_agent = self.installation.active_agent_path()?;
        if !active_agent.is_file() {
            return Err(UpdateError::HealthCheckFailed(
                "active immutable agent is missing".to_owned(),
            ));
        }

        let expected_autostart = AutostartEntry {
            owner: AUTOSTART_OWNER.to_owned(),
            command: format!("\"{}\"", self.installation.stable_agent_entry().display()),
        };
        if let Some(actual) = autostart.read().map_err(UpdateError::io)? {
            if actual != expected_autostart {
                return Err(UpdateError::AutostartOwnershipDrift);
            }
        }

        if let Some(transaction) = self.read_transaction()? {
            if !transaction.phase.is_terminal() {
                return Err(UpdateError::UnreconciledTransaction(transaction.phase));
            }
            let expected = if transaction.phase == UpdatePhase::Committed {
                &transaction.requested_version
            } else {
                &transaction.previous_version
            };
            if active != *expected {
                return Err(UpdateError::ActiveVersionDrift {
                    expected: expected.clone(),
                    actual: active,
                });
            }
            self.ensure_terminal_receipt(
                &transaction,
                if transaction.phase == UpdatePhase::Committed {
                    UpdateOutcome::Committed
                } else {
                    UpdateOutcome::RolledBack
                },
                expected,
            )?;
        }

        Ok(CumulativeProductizationAudit {
            ownership_ledger_valid: true,
            foreign_content_refusal_enforced: true,
            drift_refusal_enforced: true,
            atomic_transition_journal_valid: true,
            autostart_target_owned: true,
            active_pointer_valid: true,
            durable_transaction_reconciled: true,
            rollback_state_recoverable: true,
        })
    }

    pub fn transaction(&self) -> Result<Option<UpdateTransaction>, UpdateError> {
        self.read_transaction()
    }

    pub fn receipt(&self) -> Result<Option<UpdateReceipt>, UpdateError> {
        self.read_json(self.receipt_path())
    }

    fn verify_health(&self, health: &HealthObservation) -> Result<(), UpdateError> {
        let _ = self.installation.active_agent_path()?;
        match health {
            HealthObservation::Healthy => Ok(()),
            HealthObservation::Unhealthy(reason) => {
                Err(UpdateError::HealthCheckFailed(reason.clone()))
            }
        }
    }

    fn ensure_no_inflight_transaction(&self) -> Result<(), UpdateError> {
        if let Some(transaction) = self.read_transaction()? {
            if !transaction.phase.is_terminal() {
                return Err(UpdateError::UnreconciledTransaction(transaction.phase));
            }
        }
        Ok(())
    }

    fn active_version(&self) -> Result<String, UpdateError> {
        self.installation
            .state()?
            .active_version
            .ok_or(UpdateError::NoPreviousVersion)
    }

    fn transaction_path(&self) -> PathBuf {
        self.installation
            .root()
            .join("state")
            .join(TRANSACTION_FILE)
    }

    fn receipt_path(&self) -> PathBuf {
        self.installation.root().join("state").join(RECEIPT_FILE)
    }

    fn read_transaction(&self) -> Result<Option<UpdateTransaction>, UpdateError> {
        self.read_json(self.transaction_path())
    }

    fn read_json<T>(&self, path: PathBuf) -> Result<Option<T>, UpdateError>
    where
        T: for<'a> Deserialize<'a>,
    {
        match fs::read(&path) {
            Ok(bytes) => serde_json::from_slice(&bytes)
                .map(Some)
                .map_err(|error| UpdateError::DamagedJournal(error.to_string())),
            Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(None),
            Err(error) => Err(UpdateError::io(error)),
        }
    }

    fn write_transaction(&self, transaction: &UpdateTransaction) -> Result<(), UpdateError> {
        if transaction.schema_version != UPDATE_SCHEMA_VERSION {
            return Err(UpdateError::DamagedJournal(
                "unsupported transaction schema".to_owned(),
            ));
        }
        self.write_json(self.transaction_path(), transaction)
    }

    fn write_receipt(
        &self,
        transaction: &UpdateTransaction,
        outcome: UpdateOutcome,
        active_version: &str,
    ) -> Result<UpdateReceipt, UpdateError> {
        let receipt = UpdateReceipt {
            schema_version: UPDATE_SCHEMA_VERSION,
            transaction_id: transaction.transaction_id.clone(),
            outcome,
            active_version: active_version.to_owned(),
            poststate_reconciled: true,
        };
        self.write_json(self.receipt_path(), &receipt)?;
        Ok(receipt)
    }

    fn ensure_terminal_receipt(
        &self,
        transaction: &UpdateTransaction,
        outcome: UpdateOutcome,
        active_version: &str,
    ) -> Result<(), UpdateError> {
        if let Some(receipt) = self.receipt()? {
            if receipt.transaction_id == transaction.transaction_id
                && receipt.outcome == outcome
                && receipt.active_version == active_version
                && receipt.poststate_reconciled
            {
                return Ok(());
            }
        }
        self.write_receipt(transaction, outcome, active_version)?;
        Ok(())
    }

    fn write_json<T: Serialize>(&self, path: PathBuf, value: &T) -> Result<(), UpdateError> {
        let bytes = serde_json::to_vec_pretty(value)
            .map_err(|error| UpdateError::DamagedJournal(error.to_string()))?;
        atomic_write(&path, &bytes).map_err(UpdateError::io)
    }
}

#[derive(Debug)]
pub enum UpdateError {
    Installation(InstallError),
    Io(String),
    ChecksumMismatch { expected: String, actual: String },
    Incompatible,
    NoPreviousVersion,
    SameVersion(String),
    VersionAlreadyInstalled(String),
    NoTransaction,
    UnexpectedPhase(UpdatePhase),
    UnreconciledTransaction(UpdatePhase),
    ActiveVersionDrift { expected: String, actual: String },
    HealthCheckFailed(String),
    AutostartOwnershipDrift,
    DamagedJournal(String),
    InvalidPayload(String),
}

impl UpdateError {
    fn io(error: io::Error) -> Self {
        Self::Io(error.to_string())
    }
}

impl From<InstallError> for UpdateError {
    fn from(error: InstallError) -> Self {
        Self::Installation(error)
    }
}

impl fmt::Display for UpdateError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Installation(error) => write!(formatter, "installation failed: {error}"),
            Self::Io(error) => write!(formatter, "update I/O failed: {error}"),
            Self::ChecksumMismatch { expected, actual } => {
                write!(
                    formatter,
                    "payload checksum mismatch: expected {expected}, got {actual}"
                )
            }
            Self::Incompatible => {
                formatter.write_str("update is incompatible with this installation")
            }
            Self::NoPreviousVersion => formatter.write_str("no prior validated version is active"),
            Self::SameVersion(version) => write!(formatter, "update already active at {version}"),
            Self::VersionAlreadyInstalled(version) => {
                write!(
                    formatter,
                    "immutable version slot already exists: {version}"
                )
            }
            Self::NoTransaction => formatter.write_str("no durable update transaction exists"),
            Self::UnexpectedPhase(phase) => {
                write!(formatter, "operation is not allowed in {phase:?}")
            }
            Self::UnreconciledTransaction(phase) => {
                write!(
                    formatter,
                    "durable transaction must be reconciled from {phase:?}"
                )
            }
            Self::ActiveVersionDrift { expected, actual } => {
                write!(
                    formatter,
                    "active-version drift: expected {expected}, got {actual}"
                )
            }
            Self::HealthCheckFailed(reason) => write!(formatter, "health check failed: {reason}"),
            Self::AutostartOwnershipDrift => {
                formatter.write_str("autostart target is not the owned stable entry")
            }
            Self::DamagedJournal(reason) => {
                write!(formatter, "durable journal is damaged: {reason}")
            }
            Self::InvalidPayload(reason) => write!(formatter, "invalid update payload: {reason}"),
        }
    }
}

impl std::error::Error for UpdateError {}

/// Hashes the full staged directory in deterministic relative-path order.
/// Links, non-files, and path escapes are rejected rather than dereferenced.
pub fn payload_sha256(payload: &Path) -> Result<String, UpdateError> {
    if !payload.is_dir() {
        return Err(UpdateError::InvalidPayload(format!(
            "payload is not a directory: {}",
            payload.display()
        )));
    }
    let mut files = BTreeMap::new();
    collect_payload_hashes(payload, payload, &mut files)?;
    if files.is_empty() {
        return Err(UpdateError::InvalidPayload("payload is empty".to_owned()));
    }
    let mut hasher = Sha256::new();
    for (relative, digest) in files {
        hasher.update(relative.as_bytes());
        hasher.update([0]);
        hasher.update(digest.as_bytes());
        hasher.update([0]);
    }
    Ok(format!("{:X}", hasher.finalize()))
}

fn collect_payload_hashes(
    root: &Path,
    current: &Path,
    files: &mut BTreeMap<String, String>,
) -> Result<(), UpdateError> {
    for entry in fs::read_dir(current).map_err(UpdateError::io)? {
        let entry = entry.map_err(UpdateError::io)?;
        let kind = entry.file_type().map_err(UpdateError::io)?;
        let path = entry.path();
        if kind.is_symlink() {
            return Err(UpdateError::InvalidPayload(format!(
                "symbolic links are not accepted: {}",
                path.display()
            )));
        }
        if kind.is_dir() {
            collect_payload_hashes(root, &path, files)?;
        } else if kind.is_file() {
            let relative = path
                .strip_prefix(root)
                .map_err(|error| UpdateError::InvalidPayload(error.to_string()))?;
            let key = relative_key(relative)?;
            files.insert(key, file_sha256(&path)?);
        } else {
            return Err(UpdateError::InvalidPayload(format!(
                "unsupported payload entry: {}",
                path.display()
            )));
        }
    }
    Ok(())
}

fn relative_key(path: &Path) -> Result<String, UpdateError> {
    if path.components().any(|component| {
        matches!(
            component,
            Component::ParentDir | Component::Prefix(_) | Component::RootDir
        )
    }) {
        return Err(UpdateError::InvalidPayload(path.display().to_string()));
    }
    path.to_str()
        .map(|value| value.replace('\\', "/"))
        .ok_or_else(|| UpdateError::InvalidPayload(path.display().to_string()))
}

fn file_sha256(path: &Path) -> Result<String, UpdateError> {
    let mut file = fs::File::open(path).map_err(UpdateError::io)?;
    let mut hasher = Sha256::new();
    let mut buffer = [0_u8; 16 * 1024];
    loop {
        let read = file.read(&mut buffer).map_err(UpdateError::io)?;
        if read == 0 {
            break;
        }
        hasher.update(&buffer[..read]);
    }
    Ok(format!("{:X}", hasher.finalize()))
}

fn atomic_write(path: &Path, bytes: &[u8]) -> io::Result<()> {
    let parent = path
        .parent()
        .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidInput, "journal path has no parent"))?;
    fs::create_dir_all(parent)?;
    let temporary = parent.join(format!(
        ".{}.{}.tmp",
        path.file_name()
            .and_then(|name| name.to_str())
            .unwrap_or("runnermesh-update"),
        unique_suffix()
    ));
    fs::write(&temporary, bytes).map_err(|error| {
        io::Error::new(
            error.kind(),
            format!(
                "write durable journal {} failed: {error}",
                temporary.display()
            ),
        )
    })?;
    {
        let file = fs::OpenOptions::new()
            .read(true)
            .write(true)
            .open(&temporary)
            .map_err(|error| {
                io::Error::new(
                    error.kind(),
                    format!(
                        "open durable journal {} failed: {error}",
                        temporary.display()
                    ),
                )
            })?;
        file.sync_all().map_err(|error| {
            io::Error::new(
                error.kind(),
                format!(
                    "sync durable journal {} failed: {error}",
                    temporary.display()
                ),
            )
        })?;
    }
    replace_file(&temporary, path).map_err(|error| {
        io::Error::new(
            error.kind(),
            format!(
                "replace durable journal {} -> {} failed: {error}",
                temporary.display(),
                path.display()
            ),
        )
    })
}

#[cfg(windows)]
fn replace_file(temporary: &Path, destination: &Path) -> io::Result<()> {
    use std::os::windows::ffi::OsStrExt;
    use windows_sys::Win32::Storage::FileSystem::{
        MoveFileExW, MOVEFILE_REPLACE_EXISTING, MOVEFILE_WRITE_THROUGH,
    };

    let temporary: Vec<u16> = temporary
        .as_os_str()
        .encode_wide()
        .chain(std::iter::once(0))
        .collect();
    let destination: Vec<u16> = destination
        .as_os_str()
        .encode_wide()
        .chain(std::iter::once(0))
        .collect();
    // SAFETY: both buffers are nul-terminated and remain alive for the call.
    let result = unsafe {
        MoveFileExW(
            temporary.as_ptr(),
            destination.as_ptr(),
            MOVEFILE_REPLACE_EXISTING | MOVEFILE_WRITE_THROUGH,
        )
    };
    if result == 0 {
        return Err(io::Error::last_os_error());
    }
    Ok(())
}

#[cfg(not(windows))]
fn replace_file(temporary: &Path, destination: &Path) -> io::Result<()> {
    fs::rename(temporary, destination)
}

fn unique_suffix() -> u128 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos()
}

fn unique_transaction_id() -> String {
    format!("update-{:032X}", unique_suffix())
}

#[cfg(test)]
mod tests {
    use std::{
        fs,
        path::{Path, PathBuf},
        time::{SystemTime, UNIX_EPOCH},
    };

    use crate::{
        installation::{AutostartBackend, AutostartEntry, SandboxAutostartBackend},
        HealthObservation, Installation, UpdateCoordinator, UpdateError, UpdateOutcome,
        UpdatePhase, UpdateRequest,
    };

    use super::payload_sha256;

    fn temp_root(name: &str) -> PathBuf {
        let root = std::env::temp_dir().join(format!(
            "runnermesh-update-{name}-{}",
            SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        fs::create_dir_all(&root).unwrap();
        root
    }

    fn payload(root: &Path, name: &str) -> PathBuf {
        let payload = root.join(format!("payload-{name}"));
        fs::create_dir_all(&payload).unwrap();
        fs::write(
            payload.join("runnermesh-agent.exe"),
            format!("agent-{name}"),
        )
        .unwrap();
        fs::write(payload.join("runnermesh.exe"), format!("cli-{name}")).unwrap();
        payload
    }

    fn ready_fixture(name: &str) -> (PathBuf, UpdateCoordinator, PathBuf, SandboxAutostartBackend) {
        let root = temp_root(name);
        let installation = Installation::new(root.join("installed"));
        installation
            .install("0.1.0", &payload(&root, "old"))
            .unwrap();
        let candidate = payload(&root, "new");
        let coordinator = UpdateCoordinator::new(installation);
        let autostart = SandboxAutostartBackend::new(root.join("autostart.json"));
        (root, coordinator, candidate, autostart)
    }

    fn stage(coordinator: &UpdateCoordinator, candidate: &Path) {
        let request = UpdateRequest::new("0.2.0", candidate, payload_sha256(candidate).unwrap());
        let transaction = coordinator.stage(&request).unwrap();
        assert_eq!(transaction.phase, UpdatePhase::ReadyToActivate);
        assert_eq!(
            coordinator
                .installation()
                .state()
                .unwrap()
                .active_version
                .as_deref(),
            Some("0.1.0")
        );
    }

    #[test]
    fn table_driven_failure_injection_preserves_old_version_and_truthful_receipts() {
        #[derive(Clone, Copy)]
        enum Case {
            Checksum,
            Compatibility,
            DeferredForActiveJob,
            Health,
            InterruptedParentOrHelper,
            Commit,
        }

        for (name, case) in [
            ("checksum", Case::Checksum),
            ("compatibility", Case::Compatibility),
            ("deferred", Case::DeferredForActiveJob),
            ("health", Case::Health),
            ("interrupted-parent-helper", Case::InterruptedParentOrHelper),
            ("commit", Case::Commit),
        ] {
            let (_root, coordinator, candidate, autostart) = ready_fixture(name);
            let expected = payload_sha256(&candidate).unwrap();
            match case {
                Case::Checksum => {
                    let request = UpdateRequest::new("0.2.0", &candidate, "BAD-CHECKSUM");
                    assert!(matches!(
                        coordinator.stage(&request),
                        Err(UpdateError::ChecksumMismatch { .. })
                    ));
                    assert_eq!(
                        coordinator
                            .installation()
                            .state()
                            .unwrap()
                            .active_version
                            .as_deref(),
                        Some("0.1.0")
                    );
                    assert!(coordinator.transaction().unwrap().is_none());
                }
                Case::Compatibility => {
                    let mut request = UpdateRequest::new("0.2.0", &candidate, expected);
                    request.compatible = false;
                    assert!(matches!(
                        coordinator.stage(&request),
                        Err(UpdateError::Incompatible)
                    ));
                    assert_eq!(
                        coordinator
                            .installation()
                            .state()
                            .unwrap()
                            .active_version
                            .as_deref(),
                        Some("0.1.0")
                    );
                    assert!(coordinator.transaction().unwrap().is_none());
                }
                Case::DeferredForActiveJob => {
                    stage(&coordinator, &candidate);
                    let receipt = coordinator
                        .activate(true, HealthObservation::Healthy)
                        .unwrap();
                    assert_eq!(receipt.outcome, UpdateOutcome::DeferredForActiveJob);
                    assert_eq!(
                        coordinator.transaction().unwrap().unwrap().phase,
                        UpdatePhase::DeferredForActiveJob
                    );
                    let recovered = coordinator.reconcile().unwrap();
                    assert_eq!(recovered.outcome, UpdateOutcome::RecoveredRollback);
                    assert_eq!(recovered.active_version, "0.1.0");
                }
                Case::Health => {
                    stage(&coordinator, &candidate);
                    let receipt = coordinator
                        .activate(
                            false,
                            HealthObservation::Unhealthy("fixture failure".to_owned()),
                        )
                        .unwrap();
                    assert_eq!(receipt.outcome, UpdateOutcome::RolledBack);
                    assert_eq!(
                        coordinator
                            .installation()
                            .state()
                            .unwrap()
                            .active_version
                            .as_deref(),
                        Some("0.1.0")
                    );
                    assert!(coordinator.receipt().unwrap().unwrap().poststate_reconciled);
                }
                Case::InterruptedParentOrHelper => {
                    stage(&coordinator, &candidate);
                    // Simulate an interruption after the durable ready record but
                    // before the switched phase was recorded.
                    coordinator.installation().select_active("0.2.0").unwrap();
                    let recovered = coordinator.reconcile().unwrap();
                    assert_eq!(recovered.outcome, UpdateOutcome::RecoveredRollback);
                    assert_eq!(
                        coordinator
                            .installation()
                            .state()
                            .unwrap()
                            .active_version
                            .as_deref(),
                        Some("0.1.0")
                    );
                    assert!(coordinator.receipt().unwrap().unwrap().poststate_reconciled);
                }
                Case::Commit => {
                    stage(&coordinator, &candidate);
                    let receipt = coordinator
                        .activate(false, HealthObservation::Healthy)
                        .unwrap();
                    assert_eq!(receipt.outcome, UpdateOutcome::Committed);
                    let reconciled = coordinator.reconcile().unwrap();
                    assert_eq!(reconciled.outcome, UpdateOutcome::Committed);
                    assert_eq!(reconciled.active_version, "0.2.0");
                }
            }
            if !matches!(case, Case::Checksum | Case::Compatibility) {
                assert!(!coordinator
                    .installation()
                    .install_autostart(&autostart)
                    .unwrap());
                let audit = coordinator
                    .cumulative_productization_audit(&autostart)
                    .unwrap();
                assert!(audit.ownership_ledger_valid);
                assert!(audit.atomic_transition_journal_valid);
                assert!(audit.rollback_state_recoverable);
            }
        }
    }

    #[test]
    fn stale_intent_reconciles_without_overwriting_foreign_autostart() {
        let (_root, coordinator, candidate, autostart) = ready_fixture("stale");
        stage(&coordinator, &candidate);
        autostart
            .write(&AutostartEntry {
                owner: "foreign".to_owned(),
                command: "foreign.exe".to_owned(),
            })
            .unwrap();
        let receipt = coordinator.reconcile().unwrap();
        assert_eq!(receipt.outcome, UpdateOutcome::RecoveredRollback);
        assert_eq!(
            autostart.read().unwrap().unwrap().command,
            "foreign.exe",
            "recovery never overwrites autostart"
        );
        assert!(matches!(
            coordinator.cumulative_productization_audit(&autostart),
            Err(UpdateError::AutostartOwnershipDrift)
        ));
    }

    #[test]
    fn active_version_drift_is_refused_instead_of_guessing_a_recovery_target() {
        let (_root, coordinator, candidate, _autostart) = ready_fixture("drift");
        stage(&coordinator, &candidate);
        let third_root = temp_root("third");
        let third = payload(&third_root, "third");
        coordinator.installation().install("0.3.0", &third).unwrap();
        coordinator.installation().select_active("0.3.0").unwrap();
        assert!(matches!(
            coordinator.reconcile(),
            Err(UpdateError::ActiveVersionDrift { .. })
        ));
    }
}
